### ISSUE TITLE
Support for fault-tolerant parsers (IDE integration)

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#1]
It should be fantastic if the JavaCC could generate a fault tolerant parser which is a required features to integrate it in an IDE/Editor.

Here some interesting links about this topic:

 * https://github.com/microsoft/tolerant-php-parser/blob/master/docs/HowItWorks.md#how-it-works
 * https://arxiv.org/pdf/1806.11150.pdf
 * https://billfen.wordpress.com/incremental-parsing-and-ast-repair-with-javacc-and-jjtree/

**Comment by angelozerr** [comment]
Chevrotain which is javascript parser (without generation) explains their strategy about fault tolerant at https://sap.github.io/chevrotain/docs/tutorial/step4_fault_tolerance.html#introduction

I think it can be interesting to read.

**Comment by angelozerr** [comment]
@revusky I love IJ feature with `recoverWhile` https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md#22-using-recoverwhile-attribute

IMHO I think we should have this same feature in javacc21 and perhaps `pin`.

**Comment by revusky** [comment]
This is basically implemented (a year after this feature request, I admit, so it took a while!) and I honestly think that my implementation is more elegant. I will try to get the error collection API working quite soon. But I really did have to finish the rewriting of the lexical `generation stuff, which was the last major piece that was not rewritten yet.
