### ISSUE TITLE
Add `getKind()` and isKindOf(NodeKind kind) methods in generated `Node`

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#10]
When we loop for node in the AST and we want to check that a node is a kind node, we need to check with instanceof the class type. 

There is a sample at https://github.com/javacc21/javacc21/blob/17236da85a9d6fa883170671bedebfdbf6e4a708/src/java/javacc/Grammar.java#L280

It should be better to have a `NodeKind  Node#getKind()` and `Node.isKindOf(NodeKind kind)` which returns the generated `NodeKind`  and we could write:

```java
if (child.isKindOf(NodeKind.PackageDeclaration) || childchild.isKindOf(NodeKind.ImportDeclaration)) { 
```

**Comment by revusky** [comment]
I'm dubious on this. I am under the impression that `instanceof` is actually quite fast on a modern JVM. This is from over a year ago, and we really need feature requests that are more based on real experience of trying to use the tool, not just speculation that maybe something or other would be nice.
