### ISSUE TITLE
Is this copyLocationInfo() operation the wrong way around?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#101]
https://github.com/javacc21/javacc21/blob/2d336ea3e102e8e6cdc7f821398be42d9173511e/src/ftl/java/Token.java.ftl#L300-L303
This looks wrong - IMO it should be `merged.copyLocationInfo(t1)`. I thought I should just check before changing it.

**Comment by revusky** [comment]
Yeah, I'm pretty sure you're right. It's the wrong way round. So, yes, feel free to fix it. By all means. 

One funny aspect of all this is that this is not used anywhere currently. I was using these split and merge things to handle the >> and >>> tokens as described [here](https://javacc.com/2020/10/20/context-sensitive-tokenization/) and in that article under "The Current Solution" you see the code snippet that used this split/merge stuff. But I have a better way of dealing with this now with ACTIVATE_TOKENS and DEACTIVATE_TOKENS, so these methods don't seem to be used anywhere now. Were you thinking of using these methods yourself?

**Comment by vsajip** [comment]
> Were you thinking of using these methods yourself?

No, I was just looking at the Python translations, and noticed the inversion. I guess I can just comment them out or omit them. There's other stuff that seems never to be used, e.g. `{Node,BaseNode}.clearChildren()`.

**Comment by vsajip** [comment]
Also:
https://github.com/javacc21/javacc21/blob/2d336ea3e102e8e6cdc7f821398be42d9173511e/src/ftl/java/BaseNode.java.ftl#L93-L97

I don't think these belong in `BaseNode`, they should only be in `Token`, right?

**Comment by revusky** [comment]
> > Were you thinking of using these methods yourself?
> 
> No, I was just looking at the Python translations, and noticed the inversion.

I am pondering whether just to remove the methods. It is rather unlikely that anybody is using this and I'm always interested in reducing the LOC count. OTOH, these merge/split methods could be useful on occasion, even if they're not being used internally at the moment. So I'm of two minds about it.

> I guess I can just comment them out or omit them. There's other stuff that seems never to be used, e.g. `{Node,BaseNode}.clearChildren()`.

Yeah, I guess that is never used. Well, it could be generally useful and is not much baggage to carry, so... Those split/merge methods are actually more involved. Of course, I began by injecting those methods for my own purposes and then thought they were generally useful enough to warrant adding them to the Token.java.ftl template.

Not sure what to do...
