### ISSUE TITLE
LexicalException should host line, column information

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#11]
When we have a LexicalException, it's impossible to get the line column error when we try catch it.

ParseException (which is an exception) and LexicalException  (which is a runtime) could implement a interface like `ErrorRangeProvider `to returns the error range:

 * begin (line, column) 
 * end (line, column) 

```java
public interface ErrorRangeProvider {

   int getBeginLine();

   int getBeginColumn();

   int getEndLine();

   int getEndColumn();
}
```

**Comment by revusky** [comment]
LexicalException has been factored out. What happens now is that the lexical machinery produces a InvalidToken that corresponds to the input that it could not scan into a valid token. Of coure, the parser machinery, when it gets an instance of InvalidToken, can't do anything with it and throws a ParseException, so in effect, the conditions that previously produced a LexicalException now just produce a ParseException and that is actually a pretty significant simplification of the whole thing!
