### ISSUE TITLE
How do these work without equals()?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#130]
https://github.com/javacc21/javacc21/blob/898534eab70c8cff6a857444d1d7e563cb0d97e0/src/ftl/java/LookaheadRoutines.java.ftl#L275

https://github.com/javacc21/javacc21/blob/898534eab70c8cff6a857444d1d7e563cb0d97e0/src/ftl/java/LookaheadRoutines.java.ftl#L286

**Comment by revusky** [comment]
Closing this. I'm pretty sure this isn't a problem.
