### ISSUE TITLE
python examples ant build failed

### ISSUE THREAD

**Issue by apws** [javacc21/javacc21#132]
here below is bug report, I am using latest apache-ant-1.10.11

w:\~prj\211030-project-renate\javacc21-python\javacc21\examples\python>ant
Buildfile: w:\~prj\211030-project-renate\javacc21-python\javacc21\examples\python\build.xml

parser-check:

parser-gen:

compile:
    [javac] Compiling 120 source files
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 8
    [javac] w:\~prj\211030-project-renate\javacc21-python\javacc21\examples\python\org\parsers\python\PythonLexer.java:65: error: incompatible types: FileLineMap cannot be converted to String
    [javac]             Token invalidDedent= new InvalidToken("Invalid Dedent", input_stream);
    [javac]                                                                     ^
    [javac] w:\~prj\211030-project-renate\javacc21-python\javacc21\examples\python\org\parsers\python\PythonLexer.java:92: error: cannot find symbol
    [javac]         indentDedent.setFileLineMap(prevToken.getFileLineMap());
    [javac]                     ^
    [javac]   symbol:   method setFileLineMap(FileLineMap)
    [javac]   location: variable indentDedent of type Token
    [javac] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
    [javac] 2 errors
    [javac] 1 warning

BUILD FAILED
w:\~prj\211030-project-renate\javacc21-python\javacc21\examples\python\build.xml:21: Compile failed; see the compiler error output for details.

**Comment by vsajip** [comment]
Please try again with the latest commit which shows working tests (for example, d1de9f9).

**Comment by vsajip** [comment]
I'll close this, as there's been no feedback.
