### ISSUE TITLE
That old DEBUG_PARSER/DEBUG_LEXER stuff

### ISSUE THREAD

**Issue by revusky** [javacc21/javacc21#133]
Does that have any future really? (Or should it?)

I just don't see it really. Who would use this kind of crude approach to investigate some elusive problem in their parser? Surely any current day developer just fires up an actual debugger and puts in a break point and... That's even what I do and I can be a pretty retro guy sometimes! But, I mean, surely no younger generation developer would bother with this stuff. They would just use an actual debugger and the generated code is not so bad to step through nowadays because all the location info is there...

I mean, all that stuff has been in there since JavaCC was first written (around 1996) when there was very limited tooling for Java. I started writing this as a private email to Vinay but then figured I'd give any lurker a chance to pipe in.

Actually, I have to admit that I introduced (just last year) an extra setting of DEBUG_FAULT_TOLERANT but I meant that mostly as a temporary measure that I would use while getting the feature nailed down, because I didn't have an error collection API well defined. (Still don't, but I am going to turn my attention to it fairly soon.)

Any thoughts?

**Comment by vsajip** [comment]
I think we could lose those.

**Comment by revusky** [comment]
Great. That stuff is all gone now.
