### ISSUE TITLE
Missing beginOffset and endOffset in InvalidNode

### ISSUE THREAD

**Issue by Blarkdackbyte** [javacc21/javacc21#134]
The beginOffset and endOffset from an InvalidNode are 0.
I think in a previous version, there were the correct information available with "getBedinColumn()" etc.

I don't know, if this is a special case or if all invalidNodes have "0" as offsets.
![image](https://user-images.githubusercontent.com/14968844/144672077-b181a3fa-84bd-4c35-855e-8db69a9828fa.png)

**Comment by revusky** [comment]
Oh, that was an oversight on my part. The InvalidNode wasn't getting its location info set. Pick up the latest version and try again.

**Comment by revusky** [comment]
No feedback from the person who filed this, but it seems like the commit from last week should resolve this. So I'm closing the issue.
