### ISSUE TITLE
OutOfBoundsException from getEndColumn() when Offset is 0

### ISSUE THREAD

**Issue by Blarkdackbyte** [javacc21/javacc21#135]
If the Offset is 0, "getEndColumn()" throws an OutOfBoundsException.
![image](https://user-images.githubusercontent.com/14968844/144673729-c561cd78-5116-49d2-a480-b9c79411ef07.png)

**Comment by revusky** [comment]
This should be fixed as well. Please verify that it is.

**Comment by revusky** [comment]
There hasn't been any feedback from the person who reported this, but I'm pretty sure that the commit from a week ago resolves this. So I'm closing the issue.
