### ISSUE TITLE
Can the NFA bitsets be made more deterministic / reproducible?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#145]
The bitsets produced for the lexer NFAs seem to vary randomly each time a lexer is generated. Can they be made more deterministic / reproducible? For example, generating a Python lexer in Java, then printing out the `currentStates` field in the lexer whenever it's set, leads to this output during a parse (initial few lines only):
```
{147, 167, 178, 224, 343, 394}
{224, 253, 394}
{224, 244, 394}
{224, 383, 394}
{185, 224, 394}
{224, 394}
{147, 167, 178, 224, 343, 394}
{224, 253, 394}
{224, 244, 394}
{224, 383, 394}
```
Whereas generating the lexer in Python from the exact same grammar leads to (for the same input file):
```
<BitSet {118, 298, 319, 323, 378, 392}>
<BitSet {158, 323, 392}>
<BitSet {159, 323, 392}>
<BitSet {323, 392, 443}>
<BitSet {323, 370, 392}>
<BitSet {323, 392}>
<BitSet {118, 298, 319, 323, 378, 392}>
<BitSet {158, 323, 392}>
<BitSet {159, 323, 392}>
<BitSet {323, 392, 443}>
```
This makes it harder than necessary to see why the two implementations might be behaving differently.

**Comment by revusky** [comment]
Hmm, it seems offhand that if you looked through the code in com.javacc.core for uses of java.util.HashSet and replaced them with java.util.LinkedHashSet, which is a HashSet that respects order of insertion, then you would probably get what you want. For example, where you have:

     Set<NfaState> epsilonMoves = new HashSet<>();

you replace it with:

     Set<NfaState> epsilonMoves = new LinkedHashSet();

Things like this. I mean, probably (I haven't tried it) replacing HashSet with LInkedHashSet in one or two key spots would make the output more deterministic. The only thing is that I don't know whether Python has a LinkedHashSet equivalent. I suppose it does. Probably, as things stand, you'll get a different ordering if you use one Java implementation over another, like it would likely be different between JDK 8 and JDK 11, for example.

**Comment by vsajip** [comment]
That shouldn't be a problem. The main need for reproducibility is to help in debugging, so it really helps only us maintainers :slightly_smiling_face:

**Comment by vsajip** [comment]
I'll close this for now, but bear in mind for the next in-depth debugging session.
