### ISSUE TITLE
Token.replaceType doesn't use input parameter

### ISSUE THREAD

**Issue by Gravelbones** [javacc21/javacc21#169]
https://github.com/javacc21/javacc21/blob/659a008027ed1e630ce8781564c289264185492f/src/ftl/java/Token.java.ftl#L330-L333

The call getType() in line 331 will get the current token type, not use the input parameter type to replace it.
Actually the input parameter is not used anywhere.

**Comment by revusky** [comment]
Yeah, you're right, of course. That is a little embarrassing. Well, it's great to have somebody actually looking at the code. The more people the better! Well, it's fixed now. That's commit b23d0e1933b0e3a8a7beffc0667ae01212d584d4
I should have put the issue number in the commit message, I realize.
