### ISSUE TITLE
ParseException can't be rethrown

### ISSUE THREAD

**Issue by Gravelbones** [javacc21/javacc21#175]
There is no constructor matching e.g.
throw new ParseException("message", parseException) for rethrowing a ParseException, with a different message.
My use case is when handling included files.

**Comment by revusky** [comment]
Well, you could always INJECT the constructor that you need, no? Something like:

      INJECT ParseException : 
      {
             @Property ParseException nestedException;

              public ParseException(String message, ParseException nestedException) {
``                      super(message);
              }
      }

(The @Property thingy generates the getter/setter pair, BTW.)

**Comment by revusky** [comment]
Oh, and here is another thought. What do you think of just making ParseException and unchecked exception (i.e. subclasses RuntimeException) by default? Maybe that would just be better.

I do note however that you can put:

      INJECT ParseException : extends RuntimeException

anywhere in your grammar and it has that effect, and it just seems okay. Of course, if it was changed that, by default, ParseException extends RuntimeException, one could do the same thing in reverse, writing:

      INJECT ParseException : extends Exception

in order for it to be a checked exception. Finally, I have doubts about the whole "checked exception" concept. The reality of things is that the vast majority of the time, the code that invokes some API that potentially throws whatever exception, it doesn't really have that much to do by catching an exception and almost always might as well just let it bubble up. What is actually more useful is try/finally, in practice... but that works the same whether it's a checked or unchecked exception, so....
