### ISSUE TITLE
Generate enum instead of int for token kind.

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#19]
Token is using int for kind. IMHO I think it should use java enum.

For Qute, to day we have a QUTEConstants liek this:

```java
public interface QUTEConstants {
	
    int EOF=0;
    // End of file
    int COMMA=1;

String[] tokenImage={"<EOF>","\",\"" ...
}
```

IMHO we should have a QUTETokenKind like this:

```java
public enum QUTETokenKind {
	
	EOF(0, "<EOF>"), COMMA(1, "\",\"");
	
	private final int index;
	private final String image;

	private QUTETokenKind (int index, String image) {
		this.index = index;
		this.image = image;
	}
	
	public int getIndex() {
		return index;
	}
	
	public String getImage() {
		return image;
	}
}
```

**Comment by revusky** [comment]
DONE!!!! To achieve this required major surgery. I feel that I achieved a major milestone now. When I think how entangled the codebase was originally and now I managed this trick of changing all those int constants to Enum everywhere in the code... Well, sometimes I even impress myself!

Well, aside from being proud of this, I would say that, as the code gets more and more clean and well-structured, it becomes ever easier to work on this, so there could be an acceleration -- I mean, in terms of _tangible progress_. Up to now, most of the forward movement has been under the hood, but now, increasingly, the changes will be visible to the end user, I think. This kind of refactoring/cleanup really creates the necessary conditions to add more real tangible features to the tool.
