### ISSUE TITLE
Improve Nodes.dump to generate JSON representation

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#20]
I would like to improve Nodes.dump to generate a JSON representation. of the node to add other information like dirty, line, column number.etc.

I need that to manage tests. Are you OK @revusky to do that? If you are OK, I will create you a PR.

**Comment by revusky** [comment]
Well, in principle, if it's useful to you. Now, on the other hand, there is maybe is no urgent need to include this in the core tool itself. I mean, if you need anything extra in Nodes, you can just inject it and then, of course, things that are generally useful can just be added by default (which means adding it to the template.) But meanwhile, you can just in your grammar do: 

INJECT(Nodes) \:
{}
{
   whatever methods you need
}
And it will be available in Nodes.java.

**Comment by revusky** [comment]
You know, the truth of this is that that Nodes.dump that I have there is just some rough and ready thing I wrote years ago. It was kind of useful as a debugging tool, even though it really is quite crude. So, that said, I would be quite happy if you (or really, anybody, but you're the only person around... :-)) took ownership of this whole problem.

**Comment by revusky** [comment]
Well, anybody can write a little visitor that runs over a tree and dumps it in whatever structure, like JSON or whatever. It's not so obvious that outputting JSON should be part of the default functionality of the tool itself.
