### ISSUE TITLE
Can we lose this now that ParseException is a RuntimeException?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#203]
https://github.com/javacc21/javacc21/blob/e551b0b580880377580a4139bfe6b728ae281a0e/src/ftl/java/ParserProductions.java.ftl#L159

I assume we can, but thought it best to check with you :smile:

**Comment by revusky** [comment]
Well, I still left an option that is `USE_CHECKED_EXCEPTION=true`, so in principle, the above line ought to become:

       [#if grammar.useCheckedException]
            if (false) throw new ParseException("Never happens!"); 
       [/#if]

Of course, almost nobody will be using that option, basically for two reasons, the first and foremost being that they don't even know about it, the second reason being that there is not much reason to turn it on (that I see) unless you really miss cluttering your code with `throws ParseException` all over the place and stuff like that. But, in any case, with the above in the template, it won't generate the line in question usually, which, yes, would be a good thing. The truth is that these kinds of things are an eyesore in the generated code. (You obviously feel the same way!)

**Comment by vsajip** [comment]
Closed in db8c700.
