### ISSUE TITLE
Set permissibleModifiers correctly in C# grammar

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#209]
Tracking issue. As per [this discussion](https://github.com/javacc21/javacc21/discussions/208#discussion-4300255).

**Comment by revusky** [comment]
So, are you going to take ownership of this?

**Comment by vsajip** [comment]
Sure, I've already started looking at it. Found an oddity which I've asked about in [this discussion](https://github.com/javacc21/javacc21/discussions/215).
