### ISSUE TITLE
Code too large reappeared

### ISSUE THREAD

**Issue by adMartem** [javacc21/javacc21#222]
I think this https://github.com/javacc21/javacc21/commit/4ccdd710c311ff75f378e8f962cf662b7e251a6a#diff-17fd93902b289a97aba4290e7a520b5127f259c271e3d77bafd9c67e1184c658 commit, specifically line 49 in CommonUtils.java.ftl caused my grammar to generate too many bytes for the static initializer.  I suspect it was a change for testing that got forgotten or something.

**Comment by revusky** [comment]
Well, there's no reason to just "suspect". :-) Have you verified it?

**Comment by revusky** [comment]
Well, I meant whether changing that 8000 back to just 8 fixed the problem. I think the reason for that was testing and it got committed as a change!

**Comment by adMartem** [comment]
Yes, changing it back to 8 did fix the problem.

**Comment by vsajip** [comment]
Whoops, sorry, this was me - I changed it while debugging something and forgot to change it back :disappointed_relieved:

**Comment by revusky** [comment]
What a pity. And now you have to commit ritual seppuku.

**Comment by vsajip** [comment]
Well actually, I think _you_ committed it before it was ready - I had done the Python generation but was still working on the C# generation :wink:

**Comment by revusky** [comment]
I commited the code but didn't commit seppuku.
