### ISSUE TITLE
Another single token optimization issue

### ISSUE THREAD

**Issue by adMartem** [javacc21/javacc21#235]
```
FoosBar : (FooNeverBar)+ =>|| | "foobar" ;
FooNeverBar : "foo" | NeverBar ;
NeverBar : SCAN {false}# => "bar";
```
The FoosBar production lookahead chooses the (FooNeverBar)+ expansion, but loops without checking the NeverBar predicate causing the parse to fail in the FooNeverBar lookahead after the first iteration (assuming the input is "foobar").

**Comment by adMartem** [comment]
Trying to work around this, it seems like there could be another problem in this area.  Modifying the FoosBar production:
`FoosBar : (FooNeverBar)+ =>|| | (SCAN ASSERT (FooNeverBar) => FooNeverBar)+ | "foobar" ;` seems to have the opposite problem with the ASSERT, in that the first iteration lookahead accepts "bar", but subsequent ones correctly disallow it.

**Comment by revusky** [comment]
I was trying to look into this today and, well, to be honest, I cannot convince myself that anything is working incorrectly. 

Certainly, the fact that in something like:

    (SCAN {someCondition() => Foobar)+

the condition is only checked from the second iteration onwards, this could be surprising I grant, and even confusing, but is actually correct. In `(Foobar)+` the first iteration of the loop is not actually a *choice point* so any predicate for the repeating of the loop only applies after the first iteration.

But, generally speaking, I was playing a bit with the example (below I have my current version, a bit modified, I was playing with variations of it..) and I was feeding it different input and, frankly, it seems like it is behaving correctly. 

Well, maybe there is something wrong here, and, you know, generally, I'm not [somebody who refuses to admit there's a bug](https://javacc.com/2020/10/28/a-bugs-life/) so if I'm just being slow here, do have another go at explaining it...

----------

    FoosBar : (FooNeverBar)+ =>|| <EOF> | ("foo" | "bar")* "foobar" <EOF> ;   
    FooNeverBar : "foo" | NeverBar ;
    NeverBar : SCAN {false}# => "bar";

    SKIP : " " ;

    INJECT PARSER_CLASS : 
   {
        public static void main(String[] args) {
            if (args.length == 0) {
                System.err.println("No input provided.");
                System.exit(1);
            }
           PARSER_CLASS parser = new PARSER_CLASS(args[0]);
           parser.FoosBar();   
           parser.rootNode().dump();
        } 
    }

**Comment by adMartem** [comment]
Ok, I finally grok this.  First of all, my example was broken due to a last-minute edit I made to change "foo" "bar" into "foobar" in the first production, thus completely eliminating the behavior I was trying to highlight.  Sorry for that.  Second, my example really was an over-reduction of my real-world case and I got caught up in how it "should" work.  Thanks for illuminating that for me.  Finally, the reason I encountered this in the first place was because of an old technique I use with JavaCC (the aboriginal version) to essentially "gate" syntax that I needed to behave differently for different contexts or COBOL dialects.  You probably remember one of my early issues involving the Device production; that was also a manifestation of this technique.  In my current case, the grammar is trying to treat "at" as a legal identifier everywhere except in the context of specific COBOL statements (there are other similar "context-sensitive" reserved words as well).  So, the real solution is to just use **token activation/deactivation** to accomplish this, which I have now done.

For this ticket's issue, I got lost in trying to find a way to make the production fail (trying SCAN, ASSERT, and FAIL) when, as you pointed out, it was simple a mistaken grammar for the case I was highlighting.  I now have deeply ingrained the notion that if no choice is required, then no lookahead predicate or assertion will (or need) be applied.  

Please accept my apology for wasting your time on this one.  I will close it as "no fix."

**Comment by adMartem** [comment]
No fix required.
