### ISSUE TITLE
Missing `NODE_PREFIX` in Parser imports when using `NODE_PACKAGE`

### ISSUE THREAD

**Issue by stbischof** [javacc21/javacc21#236]
when using:

```
PARSER_PACKAGE=parser.impl;
NODE_PACKAGE=parser.impl.tree;
NODE_PREFIX=AST;
```

the Imports of the Nodes in the parser class does not use the Prefix.

I think in this lines: a `NODE_PREFIX` is missing
https://github.com/javacc21/javacc21/blob/ea93407d53eee1604fe9d4dad6226671a1756961/src/ftl/java/Parser.java.ftl#L58-L61

**Comment by revusky** [comment]
Yes, that should be:

          import ${grammar.nodePackage}.${grammar.nodePrefix}${node};

Thanks for pointing that out. That must have been broken for a while. I guess nobody uses `NODE_PREFIX` very much. Not much reason for it if you can put all the nodes in their own package. But if it's there, it should work.

It should be fixed now.

**Comment by stbischof** [comment]
It works. 

I just found it while testing all options. 

Thx. for the really fast fix.
