### ISSUE TITLE
Lookbehind can switch to the wrong stack

### ISSUE THREAD

**Issue by adMartem** [javacc21/javacc21#237]
I tracked this down right before I had to leave on a trip, so I apologize for no exemplar.  It seems that the backwards iterator implementation can erroneously choose the wrong stack when changing direction.  I coded a change to fix it, but forgot to push it some someplace I could get to while away.  In a nutshell I think the logic for next and previous needs to be cognizant of the "active" stack, which needs to be toggled if the operation cannot be carried out on it (i.e., no next or previous item on the active stack).  What was happening was that as long as we were scanning, everything was fine, but then in subsequent deeper acceptance the lookbehind failed (after having passed in lookahead) because the "previous -> break -> next" did not find the expected non-terminal.  If this isn't clear enough, just let me know.   This is the relevant generated code that encountered the issue:

```private final boolean backscan$p3cobol_ccc$5369$20() {
        ListIterator<NonTerminalCall> stackIterator= stackIteratorBackward();
        NonTerminalCall ntc= null;
        while (stackIterator.hasNext()) {
            ntc= stackIterator.next();
            if (ntc.productionName== "ParagraphModern") {
                stackIterator.previous();
                break;
            }
            if (!stackIterator.hasNext()) return false;
        }
        if (!stackIterator.hasNext()) return false;
        ntc= stackIterator.next();
        if (ntc.productionName!="ParagraphModern") return false;
        return true;
    }
```

**Comment by adMartem** [comment]
The problem is that in the stackIteratorBackward below, the .next and .previous use the lookahead stack if possible, regardless of which stack the previous operation was using.  When the lookbehind crosses over to the parser stack and then uses previous, the lookahead iterator can satisfy the request, so that the subsequent next is also satisfied from the lookahead iterator rather than the (correct) parser stack iterator.
```
...
            public boolean hasNext() {
                return parseStackIterator.hasPrevious()||lookaheadStackIterator.hasPrevious();
            }

            public NonTerminalCall next() {
                return lookaheadStackIterator.hasPrevious()?lookaheadStackIterator.previous():
                parseStackIterator.previous();
            }

            public NonTerminalCall previous() {
                return lookaheadStackIterator.hasNext()?lookaheadStackIterator.next():
                parseStackIterator.next();
            }

            public boolean hasPrevious() {
                return lookaheadStackIterator.hasNext()||parseStackIterator.hasNext();
            } ...
```

**Comment by adMartem** [comment]
Now that I look at the stackIteratorForward, I think the problem is that the stackIteratorBackward.previous() should prefer the parseStackIterator.

**Comment by revusky** [comment]
> Now that I look at the stackIteratorForward, I think the problem is that the stackIteratorBackward.previous() should prefer the parseStackIterator.

Just eyeballing it, it seems you're probably right. There is a suspicious asymmetry here...

The actual source location where this would have to be fixed is: https://github.com/javacc21/javacc21/blob/master/src/ftl/java/ErrorHandling.java.ftl#L130

**Comment by adMartem** [comment]
Yes, I tried it and it did fix it.

**Comment by revusky** [comment]
Could you check if the same error is present in the Python and CSharp generation? You'd need to look at the appropriate templtae in src/ftl/csharp and src/ftl/python respectively.

**Comment by revusky** [comment]
Okay, I'm just going to trust you to deal with this. You should have received an invitation to have write access to the repository.

Of course, don't go crazy committing things, and if you want a review of changes, maybe better to submit a PR. But if there's something just totally obvious, then... question of judgment, I guess. And, come to think of it, if you figure out something about the code and want to add a comment to help anybody else figure it out, well, that's bound to be pretty unambiguously helpful. (Or simply improve an existing comment.)

**Comment by adMartem** [comment]
For this I'll probably submit a pull request, since I'm not sure I can test the C# and Python properly.  But in any case I won't go crazy ;-).  It does, btw look like the same problem exists with both of them.

**Comment by revusky** [comment]
It says your invite to have write access to the repository expired. I reissued the invite. Did you receive it?

**Comment by adMartem** [comment]
This has been fixed by https://github.com/javacc21/javacc21/commit/8fb5f67ae26e6d581b24c01d9513a0488ef78bb6 .
