### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#3]
Please clarify the license of JavaCC

**Comment by revusky** [comment]
License is just the BSD license, which is just the license that Sun Microsystems used when 
they released the code back in 2003. 

But, more importantly for most people, any code you generate using the tool from a grammar you write is completely unencumbered. It's just yours.

**Comment by revusky** [comment]
Notwithstanding what that Russian guy, Sitnikov thinks, I don't think there's really much of an issue here. Actually, most people only care that whatever parser they generate is theirs and there has never been any issue with that, so I think I'll close this.
