### ISSUE TITLE
Use substring when it is necessary

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#31]
Using substring can grows the memory when AST is created as soon as user type something in an editor.  

For instance the generator generate token which waits an image string in the constructor https://github.com/javacc21/javacc21/blob/707997d9543d140bc865828a98f20bff993c4a3b/src/main/resources/templates/java/ASTToken.java.ftl#L66

It should be better that token waits for start, end position and when getToken is called we do the substring with the FileLineMap.

It will avoid when an AST is canceled to do substring although image is not used.

**Comment by vsajip** [comment]
I think this is now out of date because the image is usually computed from the source.
