### ISSUE TITLE
Declare JavaCC Options in Enum

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#33]
Today options are String https://github.com/javacc21/javacc21/blob/58d75db1d3f69cd011934be6cff5ae63c78aff6c/src/main/java/com/javacc/JavaCCOptions.java#L135 and there are no constants, it's little hard to find where there are used. For instance https://github.com/javacc21/javacc21/search?l=Java&q=TREE_BUILDING_ENABLED

It should be nice of to provide a JAVACCOption like this:

```java
package com.javacc;

public enum JavaCCOption {

       public enum ValueType {
           BOOLEAN, INTEGER, STRING;
        }

	TREE_BUILDING_ENABLED("Documentation of TREE_BUILDING_ENABLED");

	private final String defaultValue;

	private final String documentation;

	private JavaCCOption(String documentation) {
		this(documentation, null);
	}

	private JavaCCOption(String documentation, String defaultValue) {
		this.defaultValue = defaultValue;
		this.documentation = documentation;
	}

	public String getName() {
		return name();
	}

	public String getDefaultValue() {
		return defaultValue;
	}

	public String getDocumentation() {
		return documentation;
	}

public ValueType getValueType() {
....
}
```

I could use this enum in toolings.

**Comment by angelozerr** [comment]
If documentation could be written in markdown it should be very nice for toolings.

**Comment by revusky** [comment]
It might be nice but I'm too busy and nobody else is going to do it. Besides, as I said in a private email already, any task you set yourself should have the concurrent goal of furthering your knowledge of the core code. This does not do that.
