### ISSUE TITLE
Infinite getNextToken() Loop

### ISSUE THREAD

**Issue by manticore-projects** [javacc21/javacc21#50]
In my Legacy Grammer, there is am injected method:
```java
JAVACODE
void error_skipto(int kind) {
  ParseException e = generateParseException();
  Token t;
  do {
    t = getNextToken();
  } while (t.kind != kind && t.kind != EOF);
}
```
Called like: `error_skipto(ST_SEMICOLON);`
The purpose is to go the the next Semicolon (or End of File), when there is a Parser Error in order to jump to the next SQL Statement, when one statement has not been parsed. That has been worked well so far.

For JavaCC21 I have rewritten that method to:
```java
//JAVACODE
INJECT PARSER_CLASS : {
    void error_skipto(TokenType type) {
      //ParseException e = generateParseException();
      TokenType tokenType;
      //int i =0;
      do {
          tokenType = nextTokenType();
          //i++;
          //if (i>1E6) 
          //  System.out.println("am stuck forever!");
      } while (type!=tokenType && TokenType.EOF!=tokenType);
    }
}    
```
Problem is: If a statement fails, this will loop forever? Why? And what would be the correct way to rewrite that?
(The commented lines has been introduced only for tracing, i believe they are self explaining. I would not expect to see any output "am stuck forever" -- ever).

**Comment by revusky** [comment]
Well, I guess the loop is infinite because it's not advancing the token. You would need to have a call to getNextToken() somewhere (directly or indirectly.)

Probably something more like:

       Token t = lastConsumedToken;
        do {
             t = nextToken(t);
        } while (t.getType() != type && t.getType() != EOF);

Now, generally speaking, this kind of crude error recovery should be obsolete because [this](https://javacc.com/2021/02/18/the-promised-land-fault-tolerant-parsing/) but admittedly, if your immediate goal is just to get the JSQLParser stuff working with minimal change...

BTW, I'm tending towards the view that, to have something really satisfactory in terms of an SQL grammar, this JSQLParser stuff needs to be torn up and rewritten. But I grant that, if your only real interest in this is to pretty-pring SQL statements, you're already going way beyond what is reasonable maybe, but I guess that's all another conversation....

**Comment by manticore-projects** [comment]
> Well, I guess the loop is infinite because it's not advancing the token. You would need to have a call to getNextToken() somewhere (directly or indirectly.)

Sorry, totally my bad. I assumed (for reasons I can't explain), that `nextTokenType` would advance the token also. I rewrote it to:

```
/JAVACODE
INJECT PARSER_CLASS : {
    void error_skipto(TokenType type) {
      //ParseException e = generateParseException();

      Token token = getNextToken();
      while (token!=null && token.getType()!=type && token.getType()!=TokenType.EOF) {
          token = token.getNextToken();
      } 
    }
}    
```

And this works.

> Now, generally speaking, this kind of crude error recovery should be obsolete because of [this](https://javacc.com/2021/02/18/the-promised-land-fault-tolerant-parsing/) but admittedly, if your immediate goal is just to get the JSQLParser stuff working with minimal change...

Noted and I certainly will look into that as soon as ALL my SQL parser tests will succeed at least one time.
 
> BTW, I'm tending towards the view that, to have something really satisfactory in terms of an SQL grammar, this JSQLParser stuff needs to be torn up and rewritten.

This is actually the objective of the exercise. But before we can make that happen, we will need to migrate first to JavaCC21 itself or we will end up with too many lose ends.

> But I grant that, if your only real interest in this is to pretty-printing SQL statements, you're already going way beyond what is reasonable maybe, but I guess that's all another conversation....

Well, it is not what I wished for but any Formatter is only as good as the used Parser and I brought a lot of fixes/improvements to the Parser already just to be able to format correctly. Step by step and we will get there, eventually.
