### ISSUE TITLE
missing generated method accept() in XXXNfaData.NfaFunction

### ISSUE THREAD

**Issue by MarcMazas** [javacc21/javacc21#63]
Running tests target, missing generated method accept() in XXXNfaData.NfaFuntion

Buildfile: C:\Devs\GitRepo\javacc21\build.xml

init:
        [echo] Join the JavaCC 21 Discussion forum at: https://parsers.org/
        [echo] Send any bug report to bugs@javacc.com and include the following information.
        [echo] JDK Version: 16 on Windows 10

parser-gen:

preprocessor-gen:

compile:

jar:
        [echo] Creating basic jarfile, using this requires a freemarker.jar in the same directory
         [jar] Building jar: C:\Devs\GitRepo\javacc21\javacc.jar

test:
        [echo] Testing the JSON Parser

clean:
      [delete] Deleting directory C:\Devs\GitRepo\javacc21\examples\json\org

parser1-gen:

parser2-gen:

compile:
       [javac] Compiling 49 source files
       [javac] warning: [options] bootstrap class path not set in conjunction with -source 8
       [javac] C:\Devs\GitRepo\javacc21\examples\json\org\parsers\jsonc\JSONCLexer.java:146: error: cannot find symbol
       [javac]                     newType= nfaFunctions[0].accept(curChar, nextStates);
       [javac]                                             ^
       [javac]   symbol:   method accept(int,BitSet)
       [javac]   location: interface NfaFunction
       [javac] C:\Devs\GitRepo\javacc21\examples\json\org\parsers\jsonc\JSONCLexer.java:151: error: cannot find symbol
       [javac]                         TokenType returnedType= nfaFunctions[nextActive].accept(curChar, nextStates);
       [javac]                                                                         ^
       [javac]   symbol:   method accept(int,BitSet)
       [javac]   location: interface NfaFunction
       [javac] C:\Devs\GitRepo\javacc21\examples\json\org\parsers\json\JSONLexer.java:145: error: cannot find symbol
       [javac]                     newType= nfaFunctions[0].accept(curChar, nextStates);
       [javac]                                             ^
       [javac]   symbol:   method accept(int,BitSet)
       [javac]   location: interface NfaFunction
       [javac] C:\Devs\GitRepo\javacc21\examples\json\org\parsers\json\JSONLexer.java:150: error: cannot find symbol
       [javac]                         TokenType returnedType= nfaFunctions[nextActive].accept(curChar, nextStates);
       [javac]                                                                         ^
       [javac]   symbol:   method accept(int,BitSet)
       [javac]   location: interface NfaFunction
       [javac] Note: Some input files use unchecked or unsafe operations.
       [javac] Note: Recompile with -Xlint:unchecked for details.
       [javac] 4 errors
       [javac] 1 warning

BUILD FAILED
C:\Devs\GitRepo\javacc21\build.xml:116: The following error occurred while executing this line:
C:\Devs\GitRepo\javacc21\examples\json\build.xml:29: Compile failed; see the compiler error output for details.

Total time: 7 seconds

**Comment by revusky** [comment]
There is no accept() method in any generated code currently. There was, but I changed the name to apply() because that seems to be the more standard Java naming. The only way you can have an accept method is if you have some older NfaData.java.ftl template lying around that it is using.

**Comment by MarcMazas** [comment]
Strange. Now it works. Don't understand what may have happened with my Git actions.

**Comment by revusky** [comment]
Well, it seems that, as a general proposition, if you run `git pull` you have to do `ant clean` when you do an initial rebuild after that. (Assuming that the `git pull` picked up any  file changes, obviously!) Frankly, that strikes me as kind of normal.

**Comment by MarcMazas** [comment]
Okay ... but ...
I use an External Tools launch configuration that runs the 2 targets, clean then compile, and I got the problem ...
So the problem is not not having run the clean target.

In both cases the XXXLexer.java (generated) file was involved.

I can understand / accept that you create the generated packages (parser & preprocessor) under a source files folder and not a generated-source files folder.
But comparing timestamps of just one generated file (XXXParser.java) against the grammar file (XXX.javacc) seems to me risky; I find it safer to compare the timestamp of the grammar file against the timestamps of all the generated grammar files and get rid of possible obscur corner cases of the ant uptodate target.
