### ISSUE TITLE
Ccan't compile the JavaCC21 source

### ISSUE THREAD

**Issue by manticore-projects** [javacc21/javacc21#64]
commit 509be713dcdd34d7b668c6015291efdc4e7b1997 (HEAD -> master, origin/master, origin/HEAD)

```
compile:
    [javac] Compiling 100 source files to /home/are/Documents/src/javacc21/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 8
    [javac] /home/are/Documents/src/javacc21/src/main/java/com/javacc/parser/JavaCCLexer.java:112: error: cannot find symbol
    [javac]                 tokenBeginLine= input_stream.getLine();
    [javac]                                             ^
    [javac]   symbol:   method getLine()
    [javac]   location: variable input_stream of type FileLineMap
    [javac] /home/are/Documents/src/javacc21/src/main/java/com/javacc/parser/JavaCCLexer.java:113: error: cannot find symbol
    [javac]                 tokenBeginColumn= input_stream.getColumn();
    [javac]                                               ^
    [javac]   symbol:   method getColumn()
    [javac]   location: variable input_stream of type FileLineMap
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /home/are/Documents/src/javacc21/src/main/java/com/javacc/parser/JavaCCParser.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 2 errors
    [javac] 1 warning

BUILD FAILED
/home/are/Documents/src/javacc21/build.xml:79: Compile failed; see the compiler error output for details.
```

**Comment by revusky** [comment]
It seems like you must have some older files lying around. Just do a fresh checkout somewhere and see what happens:
        git clone https://github.com/javacc21/javacc21.git
        cd javacc21
        ant full-test

**Comment by MarcMazas** [comment]
Same problem as issue  #63.
IMHO it is most probable that the build.xml uptodate properties are inadequate, i.e. the target files should be the grammars and the source files the generated ones (and the properties used in the opposite way).

**Comment by revusky** [comment]
It may be that the IDE is caching whatever information and you need to clean the workspace or whatever after a `git pull`. But, anyway, `ant clean jar` from the CL is pretty much guaranteed to always work. Anyway, these two dumbshits should really get a cheap gun on Ebay and take themselves out of the gene pool in the interests of eugenics.
