### ISSUE TITLE
Possible problem with whitespace-sensitive languages

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#68]
https://github.com/javacc21/javacc21/blob/47e862cd0346b10fbdaace8bb20f1196166f7bd9/src/ftl/java/ParserProductions.java.ftl#L229

I might have misunderstood, but this line appears to directly inject text from a code snippet in the grammar into the generated parser. At least, a `CodeBlock`'s `getAsString()` method just returns the result of calling `getInnerText()`. This might be problematic for where the template needs better control over the formatting of this content. No doubt there are other places where this happens - just flagging this one as I came across it.

**Comment by revusky** [comment]
Well, yes, you understood the code perfectly well. A CodeBlock is a subclass of Expansion and it just represents a block of Java code, though if we have targets going for other languages, it would be a block of code in whatever language. So what the FTL handler code does in that spot is it just inserts the code at that spot. And, yes, you're right that there are some other points in the various templates that something similar happens. And, yes, you're right that we will have to make certain adjustments for outputting Python code, for example.

BUT.... I am aware of this and actually am not terribly worried about it. I think that it will not even be very high up in difficulty of the things that have to be solved. But I'm quite happy that you're going over the code. That recursive `BuildExpansionCode` macro is actually the very heart of the code generation machinery. (There's a similar one for generating the lookahead code here: https://github.com/javacc21/javacc21/blob/47e862cd0346b10fbdaace8bb20f1196166f7bd9/src/ftl/java/LookaheadRoutines.java.ftl#L288 and really, it's all not that a big a deal, is it?

**Comment by vsajip** [comment]
Another place where changes will need to be made for other languages (which I don't believe we've discussed before) is the passing of parameters to production methods. Obviously they currently use Java types, but there will need to be some way of specifying parameter lists for other languages too.

**Comment by vsajip** [comment]
This has been dealt with - the Python generated parsers currently deal with this issue satisfactorily.
