### ISSUE TITLE
Is this method planned to be used in the future? There seem to be no uses of it currently.

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#69]
https://github.com/javacc21/javacc21/blob/47e862cd0346b10fbdaace8bb20f1196166f7bd9/src/ftl/java/TreeBuildingCode.java.ftl#L140

I found references to the condition-based variant at https://github.com/javacc21/javacc21/blob/47e862cd0346b10fbdaace8bb20f1196166f7bd9/src/ftl/java/ParserProductions.java.ftl#L178 and https://github.com/javacc21/javacc21/blob/47e862cd0346b10fbdaace8bb20f1196166f7bd9/src/ftl/java/ParserProductions.java.ftl#L185

I couldn't find any references to the count-based one. This is a question rather than an actual issue, obviously - if you'd prefer some different mechanism for me to ask, let me know. I just find it useful to use this mechanism as it's easy to point to areas of the code. Feel free to close these issues if they interfere with your workflow.

**Comment by revusky** [comment]
Well, the method is used actually. For instance, look at JavaCCParser.java, lines 14,984 and 15017 and 15051. Those come from here: https://github.com/javacc21/javacc21/blob/master/src/javacc/JavaCC.javacc#L2859-L2861

It is true that the variant that takes a boolean is much more common. I guess the thing is that the `closeCondition` can actually be an integer. And that is to create a node with precisely n children.

**Comment by vsajip** [comment]
Ah, OK. I hadn't realised that
> the closeCondition can actually be an integer.

That trick would probably need changing for languages (like Python) that don't use method overloading.
