### ISSUE TITLE
Differences in ParseException constructor behaviour

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#70]
https://github.com/javacc21/javacc21/blob/47e862cd0346b10fbdaace8bb20f1196166f7bd9/src/ftl/java/ParseException.java.ftl#L50
In the above constructor, a `callStack` parameter is passed but not copied to the instance. However, in the constructor just above it at https://github.com/javacc21/javacc21/blob/47e862cd0346b10fbdaace8bb20f1196166f7bd9/src/ftl/java/ParseException.java.ftl#L41
the parser's parsing stack is so copied. What's the reason for the difference? If a `callStack` is passed, wouldn't one expect to have it copied into the instance?

Also, in a couple of constructors where a token isn't passed, there are differences in how the instance's token is set: see https://github.com/javacc21/javacc21/blob/47e862cd0346b10fbdaace8bb20f1196166f7bd9/src/ftl/java/ParseException.java.ftl#L43-L46
and
https://github.com/javacc21/javacc21/blob/47e862cd0346b10fbdaace8bb20f1196166f7bd9/src/ftl/java/ParseException.java.ftl#L51-L52
Why this slight difference in behaviour?

**Comment by revusky** [comment]
Truth told, I look at this and am just as puzzled as you are! I think they're basically just mistakes. The constructor should, in all these cases be copying the call stack over. And, as for the one having a null check, I think it's that I ran into an NPE when testing some code and added the null check in the one constructor (the one where it was actually being hit) and didn't add it in the other.

**Comment by vsajip** [comment]
I guess with 924cd19 I can close this. BTW there's a typo in that commit message - my name's spelt Vinay, not Vijay (it's a rather more common Indian name, so I quite often get called that by mistake).
