### ISSUE TITLE
First step for supporting tolerant parser

### ISSUE THREAD

**Issue by angelozerr** [javacc21/javacc21#8]
With the Qute parser when you write a broken template like:

```java
QUTEParser parser = new QUTEParser(new StringReader("{") );
parser.Root();
```

The parser throws the exception:

```
Exception in thread "main" qute.ParseException: Encountered "<EOF>" at line 1, column 1 in input.
Was expecting:
    <C_IDENTIFIER> ...
    
	at qute.QUTEParser.generateParseException(QUTEParser.java:312)
	at qute.QUTEParser.jj_consume_token(QUTEParser.java:245)
	at qute.QUTEParser.Expression(QUTEParser.java:338)
	at qute.QUTEParser.Interpolation(QUTEParser.java:379)
	at qute.QUTEParser.Block(QUTEParser.java:695)
	at qute.QUTEParser.Root(QUTEParser.java:757)
	at Test.main(Test.java:15)

```

To start implementing tolerant parser:

 * the parse of broken template should never thrown an exception and returns the Root node (even if it is broken). 
 * the parser should maintain a list of error coming from the parse. 

My idea is to have a new setter setTolerant:

```java
QUTEParser parser = new QUTEParser(new StringReader("{") );
parser.setTolerant(true);
parser.Root();
Node rootNode = parser.rootNode();

Problem[] problems = rootNode.getProblems();
```
 
where Problem stores, the message error, the node location where there is the error like [JDT IProblem](https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/core/compiler/IProblem.java)

The idea of this issue is not to implement totally tolerant support (like retry to build the tree node when node is not closed), but just return every time a node and gives the capability to get the errors list.

**Comment by revusky** [comment]
I think this particular feedback is now quite obsolete, since it is based on some very old first pass at fault-tolerant.
