### ISSUE TITLE
Copy/paste error in examples/Java.javacc?

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#84]
I think the `++` in the message should be `--`; this is in the `PreDecrementExpression` rule.
https://github.com/javacc21/javacc21/blob/46e6636fb1c84ef62b0e50f7fdd3137620b5a220/examples/java/Java.javacc#L627

**Comment by revusky** [comment]
Yeah, that's true enough! Maybe you're being a little too deferential. The "I think" above hardly seems necessary! :-)

**Comment by vsajip** [comment]
I guess this was fixed in 90e25b7.
