### ISSUE TITLE
Duplicated INJECT declaration

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#90]
https://github.com/javacc21/javacc21/blob/48a950db745ec426db90c48060faca057445446d/examples/java/Java.javacc#L481
is a duplicate of
https://github.com/javacc21/javacc21/blob/48a950db745ec426db90c48060faca057445446d/examples/java/Java.javacc#L474
and ought to be removed.

**Comment by revusky** [comment]
Well, yeah. I think you should feel free to correct something like that directly yourself.

**Comment by vsajip** [comment]
OK, I'll do that.
